name: Container Scan

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  trivy-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t myapp:latest .
      - name: Run Trivy Container Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'myapp:latest'
          format: 'table'
          exit-code: '1'
          vuln-type: 'os,library'

  grype-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t myapp:latest .
      - name: Run Grype Container Scan
        uses: anchore/scan-action@v3
        with:
          image: 'myapp:latest'
          fail-build: true

