name: Container Scan

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t myapp:latest .

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: myapp:latest
          format: sarif
          output: trivy-container.sarif
        continue-on-error: true
