name: Container Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: read
  security-events: write

jobs:
  container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trivy Container Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: my-image:latest
          format: sarif
          output: trivy-image.sarif
          severity: HIGH,CRITICAL

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-image.sarif
