name: Container Scan

permissions:
  contents: read
  security-events: write
  pull-requests: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  container-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: your-image:latest
          severity: HIGH,CRITICAL
