name: DAST Scan

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  dast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Start FastAPI app
        run: |
          pip install -r requirements.txt
          nohup uvicorn main:app --host 0.0.0.0 --port 8000 &
          sleep 10

      - name: Run OWASP ZAP baseline scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
          target: "http://localhost:8000"
