name: Dependency Scan

permissions:
  contents: read
  security-events: write
  pull-requests: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Run dependency scanning here"
