name: Dependency Scans
permissions:
  contents: read       # for checking out code
  security-events: write   # for uploading security scan results
  pull-requests: write     # if it needs to comment on PRs
on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "SPLACE"
          format: "HTML"
          out: "reports"

  trivy-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Trivy Dependency Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          security-checks: 'vuln,license'
          format: 'table'

