name: IaC Scan
permissions:
  contents: read       # for checking out code
  security-events: read   # for uploading security scan results
  pull-requests: read     # if it needs to comment on PRs
on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  checkov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Checkov IaC Scan
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          quiet: true
          soft_fail: false   # set true if you want warnings only

  trivy-iac:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Trivy IaC Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          format: 'table'
          exit-code: '1'

