name: IaC Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: read
  security-events: write

jobs:
  iac:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: bridgecrewio/checkov-action@v12
        with:
          output_format: sarif
          output_file_path: checkov-report.sarif

      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: checkov-report.sarif
