name: IaC Scan

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  iac:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Trivy IaC Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: config
          format: sarif
          output: trivy-iac.sarif
        continue-on-error: true
