name: Secrets Scan

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # Full history so Gitleaks can scan properly

      - name: Run Gitleaks (Enterprise)
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source . --no-git --exit-code 0 --report-format sarif --report-path gitleaks-report.sarif
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: gitleaks-report.sarif

      - name: Upload SARIF as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: gitleaks-results
          path: gitleaks-report.sarif
