name: Security Scans
permissions:
  contents: read
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Python Security Check with Bandit
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit (Python security scan)
        run: bandit -r .

      # Node.js Dependency Security Audit
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies and audit
        run: |
          if [ -f package.json ]; then
            npm install
            npm audit --audit-level=high
          else
            echo "No package.json found, skipping npm audit"
          fi

      # Docker Image Security Scan with Trivy
      - name: Scan repo with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          ignore-unfixed: true
          severity: HIGH,CRITICAL
