name: Security Scan

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Bandit + SARIF tools
        run: |
          pip install bandit sarif-tools

      - name: Run Bandit
        run: |
          bandit -r . -f json -o bandit.json --exit-zero
          sarif-tools convert bandit.json bandit.sarif || echo '{}' > bandit.sarif

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: bandit.sarif
